name: piper
description: "A lightweight, pure Dart state management library."
version: 0.0.1
license: MIT
homepage:

environment:
  sdk: ^3.9.2

resolution: workspace

dependencies:
  meta: ^1.11.0

dev_dependencies:
  test: ^1.24.0
  lints: ^5.0.0
