name: piper
description: "A lightweight state management library for Flutter."
version: 0.0.1
license: MIT
homepage:

environment:
  sdk: ^3.9.2
  flutter: ">=3.10.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
