name: piper
description: "A lightweight state management library for Flutter."
version: 0.0.1
license: MIT
homepage:

environment:
  sdk: ^3.9.2

resolution: workspace

dependencies:
  meta: ^1.16.0

dev_dependencies:
  lints: ^5.0.0
