name: piper
description: "A lightweight, dependency-free state management library"
version: 0.0.1
license: MIT
homepage:

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  piper:
    path: ../piper

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: