name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Pure Dart package tests
  piper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - run: dart pub get
        working-directory: packages/piper
      - run: dart analyze --fatal-infos
        working-directory: packages/piper
      - run: dart test
        working-directory: packages/piper

  # Flutter package tests
  flutter_piper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: stable
      - run: flutter pub get
      - run: flutter analyze --fatal-infos
        working-directory: packages/flutter_piper
      - run: flutter test
        working-directory: packages/flutter_piper
